In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("weather_data.csv")

In [4]:
data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

REPLACE THE AMBIGUTIES WITH SINGLE VALUE

In [6]:
new_data=data.replace(-99999, np.nan)
new_data

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [7]:
data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [10]:
new_data=data.replace([-99999, -88888], 0)
new_data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017            0          7  Sunny
2  1/3/2017           28          0   Snow
3  1/4/2017            0          7      0
4  1/5/2017           32          0   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [17]:
new_data=data.replace({
    "temperature":-99999,
    "windspeed":-99999,
    "event": '0'
}, np.nan)
new_data

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [19]:
new_data=data.replace({
    -99999: np.nan,
    -88888:np.nan
})
new_data

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [26]:
# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
new_data=data.replace({
    "temperature":"[A-Za-z]",
    "windspeed":"[A-Za-z]"
}, "", regex=True)
new_data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

# REPLACING LIST WITHOUR ANY LIST

In [27]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [28]:
#Write the code to replace score from strings to numeric, say poor:1, average:2, good: 3, exceptional: 4

In [30]:
df=df.replace({
    "score":{
    "poor":1,
    "average":2,
    "good":3,
    "exceptional":4}
})
df

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica