In [24]:
import numpy as np 
import pandas as pd

STEP NO 1 LOAD DATA SET

In [25]:
data=pd.read_csv("hourly_weather_10_days.csv")
data.head()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
0,2023-03-01 00:00:00,16.6,74.4,5.7,1012.5,9.5
1,2023-03-01 01:00:00,16.2,78.5,5.0,1012.1,10.3
2,2023-03-01 02:00:00,15.3,73.3,4.7,NaN,11.1
3,2023-03-01 03:00:00,15.8,72.4,1.3,1005.0,8.9
4,2023-03-01 04:00:00,20.9,70.6,6.8,1016.3,9.8

In [49]:
data.tail()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
235,2023-03-10 19:00:00,23.400000,67.200000,9.9,1016.900000,8.2
236,2023-03-10 20:00:00,20.200000,66.795982,8.2,1013.700000,10.3
237,2023-03-10 21:00:00,21.315789,71.400000,4.5,1001.700000,10.7
238,2023-03-10 22:00:00,20.900000,79.000000,5.0,1017.700000,8.9
239,2023-03-10 23:00:00,11.500000,66.795982,7.3,1011.884753,12.5

STEP 2 : BASIC EXPLORATION

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        240 non-null    object
 1   temperature_C    228 non-null    float64
 2   humidity_%       224 non-null    float64
 3   wind_speed_kmph  226 non-null    float64
 4   pressure_hPa     223 non-null    float64
 5   visibility_km    228 non-null    float64
dtypes: float64(5), object(1)
memory usage: 11.4+ KB

In [27]:
data.describe()

       temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  visibility_km
count     228.000000  224.000000       226.000000    223.000000     228.000000
mean       21.315789   66.795982        10.105310   1011.884753       9.989474
std         3.421237    8.190300         3.940668      5.187080       1.022166
min        11.500000   47.800000         1.300000    998.100000       6.800000
25%        18.700000   61.075000         6.625000   1008.900000       9.275000
50%        21.900000   66.300000         9.800000   1012.100000      10.000000
75%        23.925000   72.725000        13.500000   1015.100000      10.700000
max        28.700000   88.100000        17.800000   1027.000000      12.600000

In [28]:
data.isnull().sum()

timestamp           0
temperature_C      12
humidity_%         16
wind_speed_kmph    14
pressure_hPa       17
visibility_km      12
dtype: int64

handling with null values

In [45]:
data["temperature_C"].fillna(data["temperature_C"].mean(), inplace=True)
data["humidity_%"].fillna(data["humidity_%"].mean(), inplace=True)
data["wind_speed_kmph"].fillna(data["wind_speed_kmph"].mean(), inplace=True)
data["pressure_hPa"].fillna(data["pressure_hPa"].mean(), inplace=True)
data["visibility_km"].fillna(data["visibility_km"].mean(), inplace=True)

C:\Users\AL NAFIO\AppData\Local\Temp\ipykernel_3024\20519801.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["temperature_C"].fillna(data["temperature_C"].mean(), inplace=True)
C:\Users\AL NAFIO\AppData\Local\Temp\ipykernel_3024\20519801.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["humidity_%"].fillna(data["humidity_%"].mean(), inplace=True)
C:\Users\AL NAFIO\AppData\Local\Temp\ipykernel_3024\20519801.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["wind_speed_kmph"].fillna(data["wind_speed_kmph"].mean(), inplace=True)
C:\Users\AL NAFIO\AppData\Local\Temp\ipykernel_3024\20519801.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["pressure_hPa"].fillna(data["pressure_hPa"].mean(), inplace=True)
C:\Users\AL NAFIO\AppData\Local\Temp\ipykernel_3024\20519801.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["visibility_km"].fillna(data["visibility_km"].mean(), inplace=True)

In [46]:
data.isnull().sum()

timestamp          0
temperature_C      0
humidity_%         0
wind_speed_kmph    0
pressure_hPa       0
visibility_km      0
dtype: int64

In [48]:
data.isnull().sum()

timestamp          0
temperature_C      0
humidity_%         0
wind_speed_kmph    0
pressure_hPa       0
visibility_km      0
dtype: int64

step 4 data anylsis

In [50]:
data["timestamp"]=pd.to_datetime(data["timestamp"])

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        240 non-null    datetime64[ns]
 1   temperature_C    240 non-null    float64
 2   humidity_%       240 non-null    float64
 3   wind_speed_kmph  240 non-null    float64
 4   pressure_hPa     240 non-null    float64
 5   visibility_km    240 non-null    float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 11.4 KB

In [85]:
data["date"]=data["timestamp"].dt.date

In [86]:
data.columns

Index(['timestamp', 'temperature_C', 'humidity_%', 'wind_speed_kmph',
       'pressure_hPa', 'visibility_km', 'hour', 'date'],
      dtype='object')

Calculate daily /hourly average humidity

In [91]:
avg_temperature_by_date = data.groupby("date")["temperature_C"].mean()

In [92]:
print(avg_humidity_by_date)

date
2023-03-01    21.263158
2023-03-02    21.258991
2023-03-03    21.304825
2023-03-04    21.425658
2023-03-05    21.529825
2023-03-06    21.858333
2023-03-07    21.179825
2023-03-08    20.947807
2023-03-09    20.792325
2023-03-10    21.597149
Name: temperature_C, dtype: float64

In [59]:
print("\nStatistics for each weather metric:")
stats = data.describe().loc[["min", "max", "mean"]]
print(stats)

Statistics for each weather metric:
                timestamp  temperature_C  humidity_%  wind_speed_kmph  \
min   2023-03-01 00:00:00      11.500000   47.800000          1.30000
max   2023-03-10 23:00:00      28.700000   88.100000         17.80000
mean  2023-03-05 23:30:00      21.315789   66.795982         10.10531

      pressure_hPa  visibility_km  hour
min     998.100000       6.800000   0.0
max    1027.000000      12.600000  23.0
mean   1011.884753       9.989474  11.5

In [93]:

data["hour"]=data["timestamp"].dt.hour
avg_humidity_by_hour = data.groupby("hour")["humidity_%"].mean()

most_humid_hour = avg_humidity_by_hour.idxmax()
highest_humidity = avg_humidity_by_hour.max()

print("\nAverage Humidity by Hour:")
print(avg_humidity_by_hour)

print(f"\nMost humid hour: {most_humid_hour}")
print(f"Average Humidity: {highest_humidity}")

Average Humidity by Hour:
hour
0     78.170000
1     78.420000
2     72.828795
3     71.940000
4     69.310000
5     68.429598
6     65.770000
7     65.219598
8     63.490000
9     59.650000
10    58.710000
11    58.910000
12    60.159598
13    58.330000
14    61.909598
15    61.479598
16    60.319598
17    64.030000
18    66.918795
19    69.190000
20    67.419598
21    72.109598
22    73.750000
23    76.639196
Name: humidity_%, dtype: float64

Most humid hour: 1
Average Humidity: 78.41999999999999

In [62]:
data.columns

Index(['timestamp', 'temperature_C', 'humidity_%', 'wind_speed_kmph',
       'pressure_hPa', 'visibility_km', 'hour'],
      dtype='object')

In [66]:
temp=data["temperature_C"].to_numpy()
wind=data["wind_speed_kmph"].to_numpy()

In [67]:
print(temp)

[16.6        16.2        15.3        15.8        20.9        20.8
 22.8        22.5        21.2        28.2        21.31578947 25.6
 25.4        23.4        27.6        23.8        22.         23.7
 23.1        22.1        18.2        19.4        19.7        14.7
 15.9        15.7        17.6        20.         22.         21.2
 22.7        21.5        23.6        28.7        20.5        25.1
 22.1        24.5        22.6        21.9        23.9        21.31578947
 24.2        22.         19.9        18.8        16.5        18.
 13.6        15.7        18.5        15.9        25.7        20.9
 20.8        20.7        22.3        25.7        24.8        21.2
 25.5        21.9        22.4        24.7        24.4        21.31578947
 23.3        24.4        22.7        20.9        18.6        15.4
 16.7        18.7        17.9        16.         21.5        22.1
 27.1        23.7        21.9        24.2        26.8        24.4
 21.31578947 25.7        24.         19.5        23.         23.7
 19.8        21.1        18.7        20.8        19.7        15.9
 19.7        12.4        18.7        18.9        21.2        21.
 19.6        20.5        24.7        21.31578947 23.3        23.1
 22.8        24.5        24.9        24.7        24.1        22.5
 24.2        23.3        22.2        23.9        16.8        18.4
 17.8        18.5        21.1        21.9        17.9        16.6
 23.3        24.8        22.5        26.         25.4        24.3
 26.2        20.8        21.3        22.7        24.7        23.5
 25.6        23.2        23.9        15.5        19.8        17.3
 15.8        17.6        17.9        21.31578947 19.8        23.4
 19.9        25.7        23.1        25.9        24.4        22.5
 24.8        24.5        24.2        22.9        20.         20.7
 20.5        21.9        23.2        15.4        15.3        17.6
 13.5        21.31578947 17.4        14.8        21.2        18.5
 21.6        23.4        26.         22.3        21.31578947 24.9
 23.7        21.31578947 24.6        23.6        25.5        24.4
 22.5        21.5        19.         17.3        15.2        17.9
 14.3        17.3        15.6        21.5        17.8        21.2
 20.6        21.3        22.8        21.2        25.1        25.7
 27.1        25.         21.31578947 23.7        21.5        24.3
 23.6        18.6        19.6        14.7        19.         16.2
 17.7        16.3        16.8        17.3        20.         21.8
 23.3        24.4        24.1        28.5        25.8        25.3
 21.31578947 23.7        24.         22.7        24.2        22.6
 21.2        23.4        20.2        21.31578947 20.9        11.5       ]

In [68]:
print(wind)

[ 5.7         5.          4.7         1.3         6.8        10.10530973
 11.3        12.3        13.8        10.8        13.5        17.6
 16.         16.5        12.8        13.8        14.1        10.10530973
  8.1         8.          7.3         6.2         4.3         4.6
  4.4         7.7         5.3         3.2         6.2         9.7
 11.3        11.         12.8        13.4        16.3        14.1
 14.4        12.5        12.7        14.         12.8        10.10530973
  7.6         9.7         8.          6.9         5.9         4.3
  6.7         5.5         6.7         6.6         8.4         8.4
 10.9        12.8        10.3        16.7        15.8        17.8
 15.1        13.7        13.         16.3        15.2        12.7
 10.10530973  8.2         8.4         8.5         4.7         6.9
  7.3         3.2         4.          6.9         5.3         7.8
 12.7        12.7        10.10530973 11.3        13.         17.
 15.9        12.8        14.8        14.7        12.         12.2
 12.          4.7         6.5         6.4         7.3         8.2
 10.10530973  5.          4.8         6.3         5.5         6.8
  7.8        11.9        12.9        15.6        13.3        15.8
 15.4        14.1        15.6        12.3        10.10530973 10.5
  9.2         8.7        10.          5.6         7.3         6.
  6.          6.6         6.9         9.2         6.6         8.4
  8.5        10.4        10.8        13.3        13.5        14.7
 15.         16.3        13.9        12.3        12.6        10.10530973
  8.6        10.10530973  6.4        10.10530973  4.3         3.7
 10.10530973  6.6         3.7         8.6        10.10530973  9.
  8.3        11.4        11.5        13.6        15.3        16.2
 14.6        14.9        15.         13.6        10.10530973  8.7
  7.8         9.5         9.3         5.6         7.3         3.9
  6.2         5.2         5.5         6.4         7.1         8.4
  8.1        13.5        11.3        13.8        16.9        13.9
 15.3        15.2        13.6        14.2        10.6        11.3
  7.5        11.1         6.5        10.3         3.8         5.7
  6.3         4.4         5.4         5.8         8.9         7.9
 11.2         8.8        10.10530973 15.5        17.4        13.5
 14.8        17.4        12.2        13.4        15.4        11.
 10.9         6.5         7.8         6.8         4.4         6.3
  6.4         5.9         4.5         7.2         9.7        10.2
  9.6        11.6        13.1        11.5        15.4        16.5
 17.         15.7        14.9        14.9        12.3         9.1
 10.5         9.9         8.2         4.5         5.          7.3       ]

reshape into matrix form

In [84]:
temp.shape

(240,)

In [99]:
temp_matrix = temp.reshape((10,24))
print(temp_matrix)
print("minimum",temp_matrix.min(axis=1))
print("maximum",temp_matrix.max(axis=1))
print("mean",temp_matrix.mean(axis=1))

[[16.6        16.2        15.3        15.8        20.9        20.8
  22.8        22.5        21.2        28.2        21.31578947 25.6
  25.4        23.4        27.6        23.8        22.         23.7
  23.1        22.1        18.2        19.4        19.7        14.7       ]
 [15.9        15.7        17.6        20.         22.         21.2
  22.7        21.5        23.6        28.7        20.5        25.1
  22.1        24.5        22.6        21.9        23.9        21.31578947
  24.2        22.         19.9        18.8        16.5        18.        ]
 [13.6        15.7        18.5        15.9        25.7        20.9
  20.8        20.7        22.3        25.7        24.8        21.2
  25.5        21.9        22.4        24.7        24.4        21.31578947
  23.3        24.4        22.7        20.9        18.6        15.4       ]
 [16.7        18.7        17.9        16.         21.5        22.1
  27.1        23.7        21.9        24.2        26.8        24.4
  21.31578947 25.7        24.         19.5        23.         23.7
  19.8        21.1        18.7        20.8        19.7        15.9       ]
 [19.7        12.4        18.7        18.9        21.2        21.
  19.6        20.5        24.7        21.31578947 23.3        23.1
  22.8        24.5        24.9        24.7        24.1        22.5
  24.2        23.3        22.2        23.9        16.8        18.4       ]
 [17.8        18.5        21.1        21.9        17.9        16.6
  23.3        24.8        22.5        26.         25.4        24.3
  26.2        20.8        21.3        22.7        24.7        23.5
  25.6        23.2        23.9        15.5        19.8        17.3       ]
 [15.8        17.6        17.9        21.31578947 19.8        23.4
  19.9        25.7        23.1        25.9        24.4        22.5
  24.8        24.5        24.2        22.9        20.         20.7
  20.5        21.9        23.2        15.4        15.3        17.6       ]
 [13.5        21.31578947 17.4        14.8        21.2        18.5
  21.6        23.4        26.         22.3        21.31578947 24.9
  23.7        21.31578947 24.6        23.6        25.5        24.4
  22.5        21.5        19.         17.3        15.2        17.9       ]
 [14.3        17.3        15.6        21.5        17.8        21.2
  20.6        21.3        22.8        21.2        25.1        25.7
  27.1        25.         21.31578947 23.7        21.5        24.3
  23.6        18.6        19.6        14.7        19.         16.2       ]
 [17.7        16.3        16.8        17.3        20.         21.8
  23.3        24.4        24.1        28.5        25.8        25.3
  21.31578947 23.7        24.         22.7        24.2        22.6
  21.2        23.4        20.2        21.31578947 20.9        11.5       ]]
minimum [14.7 15.7 13.6 15.9 12.4 15.5 15.3 13.5 14.3 11.5]
maximum [28.2 28.7 25.7 27.1 24.9 26.2 25.9 26.  27.1 28.5]
mean [21.26315789 21.25899123 21.30482456 21.42565789 21.52982456 21.85833333
 21.17982456 20.94780702 20.79232456 21.59714912]

In [101]:
def normalize(matrix):
    mean=np.mean(matrix)
    std=np.std(matrix)
    return (matrix-mean)/std

print(normalize(temp_matrix))

[[-1.4173072  -1.53752522 -1.80801577 -1.65774325 -0.12496347 -0.15501798
   0.44607213  0.35590862 -0.03479995  2.06901543  0.          1.28759828
   1.22748927  0.62639917  1.88868839  0.74661719  0.20563609  0.71656268
   0.53623565  0.2356906  -0.93643512 -0.57578105 -0.48561753 -1.98834281]
 [-1.62768874 -1.68779775 -1.11676215 -0.39545402  0.20563609 -0.03479995
   0.41601763  0.05536356  0.68650818  2.21928795 -0.24518149  1.13732576
   0.2356906   0.95699873  0.38596312  0.17558158  0.77667169  0.
   0.86683521  0.20563609 -0.42550852 -0.75610808 -1.44736171 -0.99654413]
 [-2.31894237 -1.68779775 -0.8462716  -1.62768874  1.31765279 -0.12496347
  -0.15501798 -0.18507248  0.29579961  1.31765279  1.04716224 -0.03479995
   1.25754378  0.17558158  0.32585411  1.01710774  0.92694422  0.
   0.59634466  0.92694422  0.41601763 -0.12496347 -0.81621709 -1.77796127]
 [-1.3872527  -0.78616259 -1.02659863 -1.59763424  0.05536356  0.2356906
   1.73841587  0.71656268  0.17558158  0.86683521  1.64825235  0.92694422
   0.          1.31765279  0.8067262  -0.54572655  0.50618114  0.71656268
  -0.45556303 -0.06485446 -0.78616259 -0.15501798 -0.48561753 -1.62768874]
 [-0.48561753 -2.67959643 -0.78616259 -0.72605358 -0.03479995 -0.09490896
  -0.51567204 -0.24518149  1.01710774  0.          0.59634466  0.53623565
   0.44607213  0.95699873  1.07721675  1.01710774  0.8367807   0.35590862
   0.86683521  0.59634466  0.2657451   0.77667169 -1.35719819 -0.87632611]
 [-1.05665314 -0.8462716  -0.06485446  0.17558158 -1.02659863 -1.4173072
   0.59634466  1.04716224  0.35590862  1.40781631  1.22748927  0.89688971
   1.46792532 -0.15501798 -0.00474545  0.41601763  1.01710774  0.65645367
   1.28759828  0.56629015  0.77667169 -1.74790676 -0.45556303 -1.20692567]
 [-1.65774325 -1.11676215 -1.02659863  0.         -0.45556303  0.62639917
  -0.42550852  1.31765279  0.53623565  1.3777618   0.92694422  0.35590862
   1.04716224  0.95699873  0.86683521  0.47612664 -0.39545402 -0.18507248
  -0.24518149  0.17558158  0.56629015 -1.77796127 -1.80801577 -1.11676215]
 [-2.34899687  0.         -1.17687116 -1.9582883  -0.03479995 -0.8462716
   0.08541807  0.62639917  1.40781631  0.29579961  0.          1.07721675
   0.71656268  0.          0.98705323  0.68650818  1.25754378  0.92694422
   0.35590862  0.05536356 -0.69599907 -1.20692567 -1.83807028 -1.02659863]
 [-2.10856083 -1.20692567 -1.71785226  0.05536356 -1.05665314 -0.03479995
  -0.21512699 -0.00474545  0.44607213 -0.03479995  1.13732576  1.31765279
   1.73841587  1.10727125  0.          0.71656268  0.05536356  0.89688971
   0.68650818 -0.81621709 -0.51567204 -1.98834281 -0.69599907 -1.53752522]
 [-1.08670764 -1.50747072 -1.35719819 -1.20692567 -0.39545402  0.14552708
   0.59634466  0.92694422  0.8367807   2.15917894  1.3477073   1.19743477
   0.          0.71656268  0.8067262   0.41601763  0.86683521  0.38596312
  -0.03479995  0.62639917 -0.33534501  0.         -0.12496347 -2.95008698]]

In [74]:
mask = wind > 15

high_wind = wind[mask]

print(high_wind)

[17.6 16.  16.5 16.3 16.7 15.8 17.8 15.1 16.3 15.2 17.  15.9 15.6 15.8
 15.4 15.6 16.3 15.3 16.2 16.9 15.3 15.2 15.5 17.4 17.4 15.4 15.4 16.5
 17.  15.7]

final challange

In [ ]:

def daily_summary(matrix):
    summaries = []
    for i in range(10):
        day_summary = {
            "Day": i + 1,
            "Minimum": float(np.min(matrix[i])),
            "Maximum": float(np.max(matrix[i])),
            "Mean": float(np.mean(matrix[i]))
        }

        summaries.append(day_summary)

    return summaries


summaris = daily_summary(temp_matrix)
for day in summaris:
    print(day)

[{'Day': 1, 'Minimum': 14.7, 'Maximum': 28.2, 'Mean': 21.26}, {'Day': 2, 'Minimum': 15.7, 'Maximum': 28.7, 'Mean': 21.26}, {'Day': 3, 'Minimum': 13.6, 'Maximum': 25.7, 'Mean': 21.3}, {'Day': 4, 'Minimum': 15.9, 'Maximum': 27.1, 'Mean': 21.43}, {'Day': 5, 'Minimum': 12.4, 'Maximum': 24.9, 'Mean': 21.53}, {'Day': 6, 'Minimum': 15.5, 'Maximum': 26.2, 'Mean': 21.86}, {'Day': 7, 'Minimum': 15.3, 'Maximum': 25.9, 'Mean': 21.18}, {'Day': 8, 'Minimum': 13.5, 'Maximum': 26.0, 'Mean': 20.95}, {'Day': 9, 'Minimum': 14.3, 'Maximum': 27.1, 'Mean': 20.79}, {'Day': 10, 'Minimum': 11.5, 'Maximum': 28.5, 'Mean': 21.6}]
{'Day': 1, 'Minimum': 14.7, 'Maximum': 28.2, 'Mean': 21.263157894736846}
{'Day': 2, 'Minimum': 15.7, 'Maximum': 28.7, 'Mean': 21.258991228070176}
{'Day': 3, 'Minimum': 13.6, 'Maximum': 25.7, 'Mean': 21.304824561403507}
{'Day': 4, 'Minimum': 15.9, 'Maximum': 27.1, 'Mean': 21.425657894736844}
{'Day': 5, 'Minimum': 12.4, 'Maximum': 24.9, 'Mean': 21.52982456140351}
{'Day': 6, 'Minimum': 15.5, 'Maximum': 26.2, 'Mean': 21.858333333333334}
{'Day': 7, 'Minimum': 15.3, 'Maximum': 25.9, 'Mean': 21.17982456140351}
{'Day': 8, 'Minimum': 13.5, 'Maximum': 26.0, 'Mean': 20.947807017543862}
{'Day': 9, 'Minimum': 14.3, 'Maximum': 27.1, 'Mean': 20.792324561403507}
{'Day': 10, 'Minimum': 11.5, 'Maximum': 28.5, 'Mean': 21.59714912280702}