In [1]:

import pandas as pd

pakistani_weather = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
pakistani_weather

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [2]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [8]:
df=pd.concat([pakistani_weather, us_weather])
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [7]:
df1 = pd.concat([pakistani_weather, us_weather], ignore_index=True)
df1

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [12]:
df3 = pd.concat([pakistani_weather, us_weather], keys=["Pakistan", "US"])
df3

                city  temperature  humidity
Pakistan 0   karachi           32        80
         1    lahore           45        60
         2  peshawar           30        78
US       0  new york           21        68
         1   chicago           14        65
         2   orlando           35        75

In [14]:
df3.loc["US"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [15]:
df3.loc["Pakistan"]

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [16]:
temperature_df = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0   karachi           32
1    lahore           45
2  peshawar           30

In [17]:
windspeed_df = pd.DataFrame({
    "city": ["lahore","karachi"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

      city  windspeed
1   lahore          7
0  karachi         12

In [20]:
df_new=pd.concat([temperature_df, windspeed_df], axis=1)
df_new

       city  temperature     city  windspeed
0   karachi           32  karachi       12.0
1    lahore           45   lahore        7.0
2  peshawar           30      NaN        NaN

In [21]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [22]:
df = pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
0   karachi           32  Humid
1    lahore           45    Dry
2  peshawar           30   Rain